using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SengeleMinistries.Data;
using SengeleMinistries.Models;

namespace SengeleMinistries.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Policy = "AdminOnly")]
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // =========================================================
        // INDEX
        // GET: /Admin/Products
        // =========================================================
        public async Task<IActionResult> Index()
        {
            var products = await _context.Products
                .OrderByDescending(p => p.CreatedAt)
                .ToListAsync();

            return View(products);
        }

        // =========================================================
        // CREATE - GET
        // GET: /Admin/Products/Create
        // =========================================================
        [HttpGet]
        public IActionResult Create()
        {
            return View(new Product());
        }

        // =========================================================
        // CREATE - POST
        // POST: /Admin/Products/Create
        // =========================================================
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product product)
        {
            // These values are generated by the application,
            // not entered by the user.
            ModelState.Remove(nameof(Product.ProductId));
            ModelState.Remove(nameof(Product.CreatedAt));
            ModelState.Remove(nameof(Product.UpdatedAt));

            // Required fields
            if (string.IsNullOrWhiteSpace(product.Title))
            {
                ModelState.AddModelError(
                    nameof(Product.Title),
                    "Title is required.");
            }

            if (string.IsNullOrWhiteSpace(product.Category))
            {
                ModelState.AddModelError(
                    nameof(Product.Category),
                    "Category is required.");
            }

            if (product.Price < 0)
            {
                ModelState.AddModelError(
                    nameof(Product.Price),
                    "Price cannot be negative.");
            }

            if (!ModelState.IsValid)
            {
                return View(product);
            }

            product.CreatedAt = DateTime.UtcNow;
            product.UpdatedAt = null;

            _context.Products.Add(product);
            await _context.SaveChangesAsync();

            TempData["SuccessMessage"] =
                "Product added successfully.";

            return RedirectToAction(nameof(Index));
        }

        // =========================================================
        // EDIT - GET
        // GET: /Admin/Products/Edit/5
        // =========================================================
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var product = await _context.Products.FindAsync(id);

            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // =========================================================
        // EDIT - POST
        // POST: /Admin/Products/Edit/5
        // =========================================================
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Product product)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            ModelState.Remove(nameof(Product.CreatedAt));
            ModelState.Remove(nameof(Product.UpdatedAt));

            if (!ModelState.IsValid)
            {
                return View(product);
            }

            var existingProduct =
                await _context.Products.FindAsync(id);

            if (existingProduct == null)
            {
                return NotFound();
            }

            existingProduct.Title = product.Title;
            existingProduct.Category = product.Category;
            existingProduct.ShortDescription =
                product.ShortDescription;
            existingProduct.Description =
                product.Description;
            existingProduct.Price = product.Price;
            existingProduct.ImageUrl = product.ImageUrl;
            existingProduct.StockQuantity =
                product.StockQuantity;
            existingProduct.IsPublished =
                product.IsPublished;

            existingProduct.UpdatedAt = DateTime.UtcNow;

            await _context.SaveChangesAsync();

            TempData["SuccessMessage"] =
                "Product updated successfully.";

            return RedirectToAction(nameof(Index));
        }

        // =========================================================
        // DELETE - GET
        // GET: /Admin/Products/Delete/5
        // =========================================================
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var product = await _context.Products
                .FirstOrDefaultAsync(p => p.ProductId == id);

            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // =========================================================
        // DELETE - POST
        // POST: /Admin/Products/Delete/5
        // =========================================================
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product =
                await _context.Products.FindAsync(id);

            if (product == null)
            {
                return NotFound();
            }

            _context.Products.Remove(product);

            await _context.SaveChangesAsync();

            TempData["SuccessMessage"] =
                "Product deleted successfully.";

            return RedirectToAction(nameof(Index));
        }
    }
}